### ISSUE TITLE
fallsWithinNumericalRange falls with empty field

### ISSUE THREAD

**Issue by vasinkevych** [draperd/react-forms-processor#17]
I want to clear not required field but fallsWithinNumericalRange falls with a message `Value must be a number`
I guess it could be better to handle it with required and fail  with the string like  '   '.

**Comment by vasinkevych** [comment]
https://github.com/draperd/react-forms-processor/pull/18 and here is PR for it)

**Comment by vasinkevych** [comment]
@draperd any thoughts about the idea not to run validation for empty values. As for me, it might be easier to validate non-required fields. For example, I should include in regexp validation null/undefined and empty string for optional fields and looks like it can be covered  with `required` prop. On the other hand, I'm not sure if it works fine in all cases

**Comment by draperd** [comment]
I can see the logic in not validating a field unless a value is provided - and as you say we can cover the case of needing a value with the `required` prop. I'm also trying to think of cases where it might not work but I can't come up with any so far so I think it makes sense to add.

**Comment by draperd** [comment]
I've closed this as a result of merging #18
