### ISSUE TITLE
adding custom fields

### ISSUE THREAD

**Issue by frenchbread** [draperd/react-forms-processor#28]
Hello, thank you for the library.

Could you please provide an example on how to add custom field? (e.g. `input:file` or `input:range`)

**Comment by vasinkevych** [comment]
It can be something like: 

`
const renderer: FieldRenderer = (
    field: FieldDef,
    onChange: OnFieldChange,
    onFieldFocus: OnFieldFocus,
)  => 
switch(field.type) {
        case 'range': {
               return (<input type="range" name="someRange"  onChange={(event) => onChange()}
                        onFocus={(event) => onFieldFocus(event)}>)
       }
        case 'file': {
               return (<input type="file" name="myFile" onChange={(event) => onChange()}
                        onFocus={(event) => onFieldFocus(event)}>)
       }
        default:
            return defaultRenderer(field, onChange, onFieldFocus);

}
`

 [Here is demo page](https://draperd.github.io/react-forms-processor/) for with examples

**Comment by frenchbread** [comment]
@vasinkevych Thanks for quick reply! I'll try it.

**Comment by draperd** [comment]
Just to add some more colour to the correct answer from @vasinkevych ... the idea of the project is to create an abstraction between the form capabilities and the renderers. We are providing some renderers out of the box as an example but the idea is that people will create their own renderers that create fields however they would like.

Essentially the most simple form of a renderer is just a function with a single switch statement. It is given the properties of a field and determines how to render it. This means that you are free to define as many field types as you like and choose how you map the data provided by the core processor to specific props of the React components that you choose to render fields.

You should not consider yourself constrained to using the renderers provided by this project - in fact I would actively encourage you to build your own renderer to have complete control of your form rendering.

**Comment by philohelp** [comment]
I tried to add the above example code : 
`const renderer = (field, onChange, onFieldFocus) => {
  switch (field.type) {
    case "range": {
      return (
        <input
          type="range"
          name="someRange"
          onChange={(event) => onChange()}
          onFocus={(event) => onFieldFocus(event)}
        />
      );
    }
    default:
      return atlaskitRenderer(field, onChange, onFieldFocus);
  }
};`

I can see the range taking place in the form - but I got a "TypeError: Cannot set property 'touched' of undefined" when I try to use it. What was wrong ?
