### ISSUE TITLE
dynamic fields

### ISSUE THREAD

**Issue by frenchbread** [draperd/react-forms-processor#29]
Is it possible somehow to add/remove fields dynamically?

I've tried this:

```js
class App extends Component {

  state = {
    schema: fields // some fields list
  }

  addField = () => {
    const newField = {/*...*/}
    
    this.setState({ ...this.state, schema: [...this.state.schema, newField] })
  }

  // ...

  render () {
    return (
      <div className="Form">
          <h1>some form</h1>

          <Form renderer={atlaskitRenderer} >

            <div>
              <FormFragment defaultFields={this.state.schema} ></FormFragment>

              <span onClick={this.addField}>add field</span>
            </div>

            <FormButton label="Save" onClick={this.onClick}/>
          </Form>
        </div>
    )
  }

}

```

but the `FormFragment` does not seem to re-render (even when calling `forceUpdate()` from `addField` method)

**Comment by draperd** [comment]
It could be that there is something that needs to be changed in the code to support this use case but I'd actually like to understand why you want to do this so I can try to ensure that I take the rationale into account when making future updates.

Why would you be adding new fields to a form? Can you provide an example of where that would be required?

The core processor supports the ability to progressively show and hide fields based on the value of other fields so if you're looking for basic progressive disclosure then that should be possible by declaring all the fields initially and then revealing them in certain circumstances defined by the rules of the field (see the demos page for examples of this).

**Comment by frenchbread** [comment]
May be better calling "nested fields".

Demo example is here: [https://jsonform.github.io/jsonform/playground/index.html?example=schema-array](https://jsonform.github.io/jsonform/playground/index.html?example=schema-array)

**Comment by draperd** [comment]
I'm still not sure I understand the use case. The form builder on the demo page (https://draperd.github.io/react-forms-processor/) has an example of a "repeating" form field that allows you to repeatedly add data for a single form definition.

However, for the time being that is just a custom field that belongs to the custom renderer in the formbuilder package. 

Is that the sort of thing you're after?

**Comment by frenchbread** [comment]
Yeah, kind of.. but since formbuilder implements a single form, I actually was asking if its possible (similarly to the [example](https://jsonform.github.io/jsonform/playground/index.html?example=schema-array)) to have a `form` or `form fragment` where you have `+` & `-` buttons which allows to add/remove `form fragments` or `group of fields` dynamically. 

Simple use case of that would be when making a UI where a user can add multiple addresses (with a number of fields like `street`, `city`, `index` etc. & assuming that user can have one or more addresses,) you don't want to show all the `FormFragment`s with addresses fields initially, but instead, allow user to dynamically add addresses (with group of fields), so that it doesn't overflow the UI.

As I understood, there is no such functionality, and `FormFragment` won't re-render when dynamically adding fields to the schema.

Thank you for clearing this anyways.

**Comment by draperd** [comment]
Just to clarify - I didn't mean the output of the form builder, but rather the form builder itself. The entire form builder is just an example of a complex form built with react-forms-processor. 

The formbuilder package contains a custom field type called "repeats" (https://github.com/draperd/react-forms-processor/blob/master/packages/formbuilder/src/Repeats.js) that does exactly what you're asking for, i.e. allows you to add repeating pieces of data that corresponding through a single form that is repeated multiple times.

The main reason why it is not in the main Atlaskit package is because I wanted to keep the bundle size small. Ideally I was hoping to provide a more generic example or a helper utility or HOC that could be used to implement this type of field for multiple renderers - I just haven't gotten around to it yet.

**Comment by draperd** [comment]
Closing this as the conversation seems to have dried up on this topic.
