### ISSUE TITLE
Repopulate Form

### ISSUE THREAD

**Issue by swordsreversed** [draperd/react-forms-processor#45]
What is the preferred way to repopulate the form for editing? How are people doing this? Loop through the responses, match the ids and assign to the (default) value?

**Comment by draperd** [comment]
If you assign the `value` attribute of the `Form` component with an object map of `name` attribute to value then the fields will be populated.

So for example if I have the fields defined as

```
[
  {
    id: 'FIELD1',
    name: 'a',
    type: 'text'
  },
  {
    id: 'FIELD2',
    name: 'b',
    type: 'text'
  }
]
```

...then I could assign the `value` attribute on the `Form` component as:

```
{
  a: "value1",
  b: "value2",
}
```

**Comment by swordsreversed** [comment]
So the Form component itself can have a value attribute? eg
```
<Form defaultFields={form.fields} renderer={renderer} value={
  a: "value1",
  b: "value2"}
>
</Form>
```

**Comment by draperd** [comment]
You're missing a couple of brackets, but otherwise yes...

``` REACT
<Form defaultFields={form.fields} renderer={renderer} value={{
  a: "value1",
  b: "value2" }}> 
</Form>
```

**Comment by draperd** [comment]
See https://github.com/draperd/react-forms-processor/blob/master/packages/core/src/types/components.js#L16

**Comment by swordsreversed** [comment]
Awesome thanks.

**Comment by draperd** [comment]
No probs - happy to help, let me know if you have any more questions or feedback

**Comment by swordsreversed** [comment]
Sorry, the readme is not that clear to me and i'm having problems finishing the input to a database.

When i get my data into the form, edit and save it:

```
<Form defaultFields={form.fields} value={singleticket} renderer={renderer}>
  <FormButton
    label="Save"
    onClick={(formData) => {
    console.log(formData);
    this.props.updateTicket(formData);
  }}
  />
</Form>
```
I see the original unaltered data in formData, not the updates i've done. Obviously i'm missing a step.
