### ISSUE TITLE
Relative path dependencies in formbuilder

### ISSUE THREAD

**Issue by roffelsaurus** [draperd/react-forms-processor#55]
You are referring to relative paths here, and not the npm package. 

https://github.com/draperd/react-forms-processor/blob/ba39d8ae3adb1b5a0d001dbd151ebf9a7d59e161/packages/formbuilder/src/Repeats.js#L8

https://github.com/draperd/react-forms-processor/blob/ba39d8ae3adb1b5a0d001dbd151ebf9a7d59e161/packages/formbuilder/src/renderer.js#L3

You also need to export Expander

https://github.com/draperd/react-forms-processor/blob/ba39d8ae3adb1b5a0d001dbd151ebf9a7d59e161/packages/atlaskit/src/index.js#L8

**Comment by draperd** [comment]
Thanks for raising these points - I'll try to make the necessary updates asap.

**Comment by draperd** [comment]
The fix for this is now available in 0.0.37
