### ISSUE TITLE
Dynamic validation error message

### ISSUE THREAD

**Issue by mwesthelle** [draperd/react-forms-processor#59]
Is it possible to display a validation error message dynamically based on outside input? To paint you a picture of my use case: I want to get the value of the form, which happens to be a dropdown, cut a part of it and try to feed it back to the form schema to show in the validation error message. So, say the value is `05 - bananas`, I want the validation error to say `05 is an invalid option`.

What I tried is writing a function that gets the value as an argument and returns  `defaultFields` dynamically with the error message as a template string, but that doesn't seem to work. Am I going about this in the wrong way, or is this not possible at all?

**Comment by mwesthelle** [comment]
Please disregard this, that approach _does_ work.

**Comment by mwesthelle** [comment]
I'm sorry for reopening this. After further testing, it turns out that once the value changes, the change does not take effect instantly and the validation message is not shown. It is shown if I select the same value twice, though. I'm looking into the `defaultFieldsHaveChanged` logic, but I'd appreciate any insights you might have.

**Comment by draperd** [comment]
Apologies for taking a few days to respond to this - but thanks for taking an interest in this project, I really appreciate the feedback.

I know the documentation could be improved so you might not be aware of it if you've not dug into the source code, but have you tried providing a custom validator to the form. 

A custom validation handler (you can find the type definition [here](https://github.com/draperd/react-forms-processor/blob/master/packages/core/src/types.js#L174)) takes the current field being validated, all the fields in the form and the form context as arguments and should return an error message if it find a problem.

This approach should allow you to access the current value of the field being validated and allow it to be incorporated into any error message that you return. It also allows you to completely plugin in an alternative validation strategy if you aren't able to achieve the results you need using the options provided through field definition.

Let me know if this helps!

**Comment by draperd** [comment]
Additionally - you can find an example of a custom validation handler in the FormBuilder here: https://github.com/draperd/react-forms-processor/blob/master/packages/formbuilder/src/FormBuilder.js#L83

**Comment by mwesthelle** [comment]
Silly me, that does work pretty well! Thanks, and sorry for not digging more before opening this issue. I'll close this now.
