### ISSUE TITLE
Fetched options is not displayed in a AK select

### ISSUE THREAD

**Issue by vasinkevych** [draperd/react-forms-processor#60]
Hi, @draperd I've faced with an issue that options I fetch on componentdidMount do not display in a single select. They become after fetching to component from state but in select is displayed only initial data. I'm curious if its known issue, maybe you have a rough idea about it.

**Comment by draperd** [comment]
I've not come across this problem before - if you have a branch you can share the example with me that will help be dig into the problem some more. Does this seem like something specific to Atlaskit or is this something that you think exists in the core?

**Comment by vasinkevych** [comment]
As a solution, I've added to renderer function my own custom select which is connected to the state and fetch options on componentDidMount and get options directly from the state. 
I suppose we can close it.
