### ISSUE TITLE
React Native

### ISSUE THREAD

**Issue by rhugie** [draperd/react-forms-processor#62]
Is there a renderer for react native in the works?

**Comment by draperd** [comment]
I have no plans to create a react native renderer but would happily accept such a contribution to the project.

**Comment by rhugie** [comment]
I thought that might be the answer. That's something I will likely have to take on. Haven't look into how much effort that will be yet.

**Comment by draperd** [comment]
The amount of effort really depends on whether or not an existing React Native component library exists that can be re-used or if you need to create one from scratch. If a component library already exists then the renderer is essentially just a mapping of type to component and then the individual field props from React Forms Processor to the specific props in the component.

**Comment by rhugie** [comment]
I had a look at the other renderers. I'm about to start working on this. Is there anything special I need to know about building the code? I don't see any documentation on the site about that.

**Comment by draperd** [comment]
Sorry, it's taken a few days to get back to you.

No there's nothing particularly special. The main thing to be aware of is that's it's a Lerna monorepo. I would create a separate package for your renderer and import the core React Forms Processor package into it.

I'm not very familiar with React Native but I expect you'll have to add quite a bit of infrastructure to your package for it to be unit testable etc.
