### ISSUE TITLE
Pre-populate forms with async data

### ISSUE THREAD

**Issue by RobRomaniwArgo** [draperd/react-forms-processor#63]
I'm trying to figure out how to pre-populate the form with async data. I see how to do it with static data: 
```
<Form defaultFields={form.fields} renderer={renderer} value={{
  a: "value1",
  b: "value2" }}> 
</Form>
```

How would you recommend assigning values from an API call?

**Comment by draperd** [comment]
Hi, 

Thanks for asking this question - I've not really documented how to do this anywhere yet, but you can find an example of how to do this in the example source code here: https://github.com/draperd/react-forms-processor/blob/master/packages/examples/src/App.js#L31

Essentially you can create an options handler for that can be used to return a promise of options to populate a field with. It's a bit open ended at the moment and I did plan to provide support configuring a URL to retrieve options from (along with a configuration for identifying the options/labels/values attributes in the response) but I haven't got around to that yet (I'm doing less development generally at the moment, but this project is being maintained for bugs)

Hope this helps,

Let me know if you need further information

Regards,
Dave

**Comment by RobRomaniwArgo** [comment]
I'll take a look at this! Thanks
