### ISSUE TITLE
Uncaught TypeError in formbuilder.

### ISSUE THREAD

**Issue by jj321** [draperd/react-forms-processor#66]
Hello,

I'm trying to setup the project so i can run it locally.
I want to add a PageHeader component and modify the 'is' function or add a 'contains' function, to make it possible to check if a mult-select contains an option.
E.g., If the multi-select contains the option 'Other' i want a textfield to be shown.

However, i can't seem to get the project running locally.
When navigating to the formbuilder i get the following error:

Uncaught TypeError: t is not a function

Field.js:181 Uncaught TypeError: t is not a function
    at t.value (Field.js:181)
    at finishClassComponent (react-dom.development.js:13085)
    at updateClassComponent (react-dom.development.js:13047)
    at beginWork (react-dom.development.js:13715)
    at performUnitOfWork (react-dom.development.js:15741)
    at workLoop (react-dom.development.js:15780)
    at HTMLUnknownElement.callCallback (react-dom.development.js:100)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:138)
    at invokeGuardedCallback (react-dom.development.js:187)
    at replayUnitOfWork (react-dom.development.js:15194)

The error seems to originate from nodule_modules/@atlaskit/form/dist/esm/Field.js

Here are the steps which i have taken:

1. Downloaded source
2. Open folder in visual studio code
3. Run 'lerna bootstrap'
4. Navigate to 'packages\core'
5. 'yarn run build'
6. Navigate to 'packages\atlaskit
7. 'yarn run build'
8. Navigate to 'packages\formbuilder'
9. 'yarn run build'
10. Navigate to 'packages\material-ui'
11. 'yarn run build'
12. Navigate to 'packages\examples'
13. 'yarn run start'
14. Open localhost:3001
15. Naviage to 'Formbuilder'

Produces the above exception.

Am i missing something?

Kind regards,

Jaap

**Comment by draperd** [comment]
Hi,

Thanks for raising this issue. I just ran through the steps I usually take:

1. `yarn install`
2. `yarn bootstrap`
3. `yarn build`
4. navigate to `packages/examples`
5. `yarn start`
6. Open browser at http://localhost:3001/ 

I've tested and it does appear to work fine for me. Can you try again following the steps I've used please?

Regards,
Dave

**Comment by jj321** [comment]
Hi Dave,

Sadly it is not working yet.
Here is what i did:

I've redownloaded the code and extracted it.
I've navigated to the root of the folder (with the lerna.json file in it).
Ran: yarn install (from CMD)
Ran: yarn bootrap
Ran: yarn build

The build command gives me the following error:

14 error build Errored while running script in 'react-forms-processor'
15 error execute callback with error
16 error Error: Command failed: yarn run build
16 error error Command failed with exit code 1.
16 error error Command failed with exit code 1.
16 error $ webpack --mode production
16 error Hash: 07beefdde2ad4163cda7
16 error Version: webpack 4.8.1
16 error Time: 9226ms
16 error Built at: 2019-07-01 20:52:49
16 error        Asset      Size  Chunks             Chunk Names
16 error     index.js  51.1 KiB       0  [emitted]  index
16 error index.js.map   215 KiB       0  [emitted]  index
16 error Entrypoint index = index.js index.js.map
16 error   [3] external "react" 42 bytes {0} [built]
16 error  [13] ./src/utilities/utils.js 19.1 KiB {0} [built]
16 error  [22] (webpack)/buildin/module.js 519 bytes {0} [built]
16 error  [35] ./src/renderer.js 7.67 KiB {0} [built]
16 error  [37] ./src/utilities/validation.js 13.3 KiB {0} [built]
16 error [104] (webpack)/buildin/global.js 509 bytes {0} [built]
16 error [120] ./src/index.js 1.18 KiB {0} [built]
16 error     + 114 hidden modules
16 error $ yarn build:flow
16 error $ ../../node_modules/flow-copy-source/bin/flow-copy-source.js --verbose --ignore '**/*{story,test}.js' src dist
16 error info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
16 error info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
16 error
16 error     at E:\react-forms-processor-master\node_modules\lerna\node_modules\execa\index.js:236:11

Any idea what could be wrong?

Kind regards,

Jaap

**Comment by jj321** [comment]
Investigated a bit further.
When i remove the below lines from the packages.json file located under the core folder the build is successful! 

```
"postbuild": "yarn build:flow",
"build:flow": "../../node_modules/flow-copy-source/bin/flow-copy-source.js --verbose --ignore '**/*{story,test}.js' src dist"
```

I can also run the formbuilder example.

When running the postbuild command manually from the core folder i also get a windows script host error:

![image](https://user-images.githubusercontent.com/3462242/60461380-a7e5a680-9c46-11e9-9a9a-c20da570fca3.png)

Besides that everything seems to run OK now.

**Comment by draperd** [comment]
Sorry it's taken a few days to get back to you. I don't use Windows for development so I'm assuming the problems you're facing might be environment based. If everything seems to me working as you say I'm going to close this issue.
