### ISSUE TITLE
Mark all fields touched

### ISSUE THREAD

**Issue by blabno** [draperd/react-forms-processor#8]
When I submit the form and validation is failing I want all validation errors to be shown.
So it would be great to tell the form to mark every field as touched.

**Comment by draperd** [comment]
Thanks for raising this Bernard - and the associated PR. It's now the weekend for me (I'm in Sydney, Australia) so I won't do anything with the PR until Monday (so I can check the branch out and test it out). I've had a quick look and it looks good though so shouldn't be a problem to merge

This is definitely a good feature to add so I'm very happy that you've identified the issue and raised a PR for it - I'm really very grateful, thanks! 👍

**Comment by blabno** [comment]
This feature got broken again. It was fixed in `0.0.22` and got broken in `0.0.26`.

**Comment by draperd** [comment]
Thanks for reporting this @blabno - is it still broken in 0.0.28 ? There have been subsequent changes to validation since that commit you referenced.

I have been trying to ensure we have unit tests to cover all the conditions but it might be that we have a shortfall in the tests.

**Comment by blabno** [comment]
Yes, it exists in 28 as well.

Sent from ProtonMail mobile

-------- Original Message --------
