### ISSUE TITLE
Support to skip field touch when using onFieldChange fn

### ISSUE THREAD

**Issue by suryaVemp** [draperd/react-forms-processor#82]
I am driving some form field values through the onFieldChange function in a useEffect. This is causing the field state to be touched, but I would like the field state to retain its existing touched state.
Can we do something like this?(This snippet is from the onFieldChange fn in the src/components/Form.js )
```js  
//adding another argument skipFieldTouch
onFieldChange(id: string, value: Value, skipFieldTouch) {
    const {
      optionsHandler,
      validationHandler,
      parentContext,
      skipValidationBeforeTouched = false,
      disabled = false
    } = this.props;
    let { fields } = this.state;
    //skiping the field touch update here
    if(!skipValidationBeforeTouched)
    fields = updateFieldTouchedState(id, true, fields);
    fields = updateFieldValue(id, value, fields);
    const nextState = getNextStateFromFields({
      fields,
      lastFieldUpdated: id,
      showValidationBeforeTouched,
      formIsDisabled: disabled,
      resetTouchedState: false,
      optionsHandler,
      validationHandler,
      parentContext
    });

    this.setState(
      (state, props) => {
        return nextState;
      },
      () => {
        const { onChange } = this.props;
        const { value, isValid } = nextState;
        if (onChange) {
          onChange(value, isValid);
        }
      }
    );
  }

**Comment by draperd** [comment]
I'm on vacation at the moment. I'll take a look at this when I'm back next week.

**Comment by draperd** [comment]
This looks like a reasonable suggestion. I'm happy to accept a pull request for this (ideally with a corresponding test) so long as backwards compatibility is retained (which it looks like it would be)

**Comment by suryaVemp** [comment]
I have my pr https://github.com/draperd/react-forms-processor/pull/84 and i have a test case for it as well....

**Comment by draperd** [comment]
I've merged the PR and published a new version.  0.0.43 should contain your changes.

**Comment by draperd** [comment]
Closing this now that the PR has been merged
