### ISSUE TITLE
Disabled option doesn't work

### ISSUE THREAD

**Issue by davvvid1** [draperd/react-forms-processor#85]
I am using my custom renderer and property `disabled` is always set as `false` on `field` object, even if I set it in the field definition as `true`.
I noticed that on demo page it also doesn't work with build in renderers.
The simplest steps to reproduce are:
1. Go to https://draperd.github.io/react-forms-processor
2. Select `Live editor` tab
3. Edit first field definition in the editor box to:
```
	{
		"id": "NAME",
		"name": "name",
		"label": "Name?",
		"description": "Some additional information",
		"placeholder": "Your name...",
		"defaultValue": "Bob",
		"type": "text",
		"required": true,
		"validWhen": {
			"lengthIsGreaterThan": {
				"length": 3,
				"message": "Name is too short!"
			}
		},
		"disabled": true
	},
```
4. Check if field is disabled on the right section `Preview`

Currently, I am using my custom `readyOnly` property in field definition to use it in custom renderer and then it works as expected.

**Comment by suryaVemp** [comment]
Can you try defaultDisabled property instead ("defaultDisabled" :true)...I think the forms processor api documentation needs to be updated.

**Comment by draperd** [comment]
Yes, @suryaVemp is correct. It should be `defaultDisabled` rather than `disabled`. Apologies, I'll fix this

**Comment by draperd** [comment]
The demo page has now been corrected

**Comment by davvvid1** [comment]
Thank you! `defaultDisabled` is working correctly.
